feat(vpc): add aws_vpc_security_group_ingress/egress_rule resource
upbound/provider-aws pull request #685
Opened 2023-05-03 06:07 UTC by huynhsontung

### Description of your changes

Fixes #683

I have:

- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

2023-05-03 06:07 UTC, Upbound-CLA commented
[![CLA assistant check](https://cla.upbound.io/pull/badge/not_signed)](https://cla.upbound.io/upbound/provider-aws?pullRequest=685) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.upbound.io/upbound/provider-aws?pullRequest=685) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.upbound.io/check/upbound/provider-aws?pullRequest=685) it.</sub>

2023-05-03 06:34 UTC, jeanduplessis commented
/test-examples="examples/vpc/securitygroupegressrule.yaml,examples/vpc/securitygroupingressrule.yaml"

2023-05-03 06:46 UTC, jeanduplessis requested changes
@huynhsontung, thanks for the contribution. Two small changes please to clean up the examples.

2023-05-03 06:46 UTC, jeanduplessis commented on examples/vpc/securitygroupegressrule.yaml
> +---
@huynhsontung please remove this trailing object separator

```suggestion
```

2023-05-03 06:46 UTC, jeanduplessis commented on examples/vpc/securitygroupingressrule.yaml
> +---
Also this one please
```suggestion
```

2023-05-03 17:51 UTC, huynhsontung commented
/test-examples="examples/vpc/securitygroupegressrule.yaml,examples/vpc/securitygroupingressrule.yaml"

2023-05-03 20:27 UTC, huynhsontung commented
```
case.go:363: retrieving API resource for vpc.aws.upbound.io/v1beta1, Kind=SecurityGroupEgressRule failed: the server could not find the requested resource
case.go:363: retrieving API resource for vpc.aws.upbound.io/v1beta1, Kind=SecurityGroupIngressRule failed: the server could not find the requested resource
```

The package was built and deployed successfully but could not find the API resource. I'm not sure what is missing.

2023-05-30 01:31 UTC, huynhsontung commented
@turkenf Sorry for the late followup. I went back and updated some missing codegen configs to reference external resources correctly. However, I still get this error message regardless of what config I change.

```
cannot run refresh: refresh failed: reading VPC Security Group Rule (): InvalidSecurityGroupRuleId.Malformed: The security group rule ID '' is malformed
        status code: 400, request id: bb0840ad-3c70-4405-8c03-ffd864b68399      {"type": "Warning", "object": {"kind":"SecurityGroupEgressRule","name":"egressrule-test","uid":"1f43bf65-2d6d-4b97-af92-4e2d55b6f815","apiVersion":"vpc.aws.upbound.io/v1beta1","resourceVersion":"18950285"}, "reason": "CannotObserveExternalResource"}
```

terraform.tfstate
```json
{
  "version": 4,
  "terraform_version": "1.2.1",
  "serial": 1,
  "lineage": "1f43bf65-2d6d-4b97-af92-4e2d55b6f815",
  "outputs": null,
  "resources": [
    {
      "mode": "managed",
      "type": "aws_vpc_security_group_egress_rule",
      "name": "egressrule-test",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "cidr_ipv4": "10.0.0.0/8",
            "from_port": 80,
            "id": "", 
            "ip_protocol": "tcp",
            "security_group_id": "sg-0123456789abc",
            "tags": {
              "crossplane-kind": "securitygroupegressrule.vpc.aws.upbound.io",
              "crossplane-name": "egressrule-test",
              "crossplane-providerconfig": "default"
            },
            "to_port": 8080
          }
        }
      ]
    }
  ]
}
```

It seems that on the first reconciliation, the provider generates a stub tfstate file with an empty `id` field and Terraform doesn't like that. If I inject the SGR external name using `crossplane.io/external-name` annotation then it starts to reconcile just fine.

I am not aware of any way to customize the provider tfstate generation behaviour and am not sure where to go from here. I would appreciate some guidance on this issue.

2023-06-21 15:04 UTC, turkenf commented
My observations in this PR with provider-aws v0.36.0:

I keep getting the same error:
```
      message: "observe failed: cannot run refresh: refresh failed: reading VPC Security
      Group Rule (): InvalidSecurityGroupRuleId.Malformed: The security group rule
      ID '' is malformed\n\tstatus code: 400, request id: 39c253e2-4845-4349-8774-62a1969a27b9"
```
When I create the `egress_rule` resource in terraform with the example below:
```
resource "aws_vpc_security_group_egress_rule" "example" {
  security_group_id = "sg-0e625fc4bf678386f"

  cidr_ipv4   = "10.0.0.0/8"
  from_port   = 80
  ip_protocol = "tcp"
  to_port     = 8080
}
```
The attributes.id in the tfstate file comes as `"id": "sgr-0ec075aef37950e08",`:
```
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:ec2:us-west-1:569674547146:security-group-rule/sgr-0ec075aef37950e08",
            "cidr_ipv4": "10.0.0.0/8",
            "cidr_ipv6": null,
            "description": null,
            "from_port": 80,
            "id": "sgr-0ec075aef37950e08",
            "ip_protocol": "tcp",
            "prefix_list_id": null,
            "referenced_security_group_id": null,
            "security_group_id": "sg-0e625fc4bf678386f",
            "security_group_rule_id": "sgr-0ec075aef37950e08",
            "tags": null,
            "tags_all": {},
            "to_port": 8080
          },
          "sensitive_attributes": []
```
In our example, the `id` in the `tfstate` file is somehow empty and this causes an error and the resource is not created:
```
                    "schema_version": 0,
                    "attributes": {
                        "cidr_ipv4": "10.0.0.0/8",
                        "from_port": 80,
                        "id": "",
                        "ip_protocol": "tcp",
                        "security_group_id": "sg-0e625fc4bf678386f",
                        "tags": {
                            "crossplane-kind": "securitygroupegressrule.vpc.aws.upbound.io",
                            "crossplane-name": "example",
                            "crossplane-providerconfig": "default"
                        },
                        "to_port": 8080
```

2023-06-23 10:12 UTC, jeanduplessis commented
/test-examples="examples/vpc/securitygroupegressrule.yaml,examples/vpc/securitygroupingressrule.yaml"

2023-07-21 14:14 UTC, ulucinar commented on config/vpc/config.go
> +func Configure(p *config.Provider) {
Hi @turkenf,
We had better understand whether we still need the `SecurityGroupRule.ec2` resource as two separate ingress and egress rules are being introduced. Looking at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule, Terraform has not deprecated this resource but we may still mark it as deprecated if there are not configurations not covered by these new two resources (for instance, are there any other rule types other than ingress and egress, etc.)?

2023-09-28 00:15 UTC, huynhsontung commented
@turkenf @ulucinar I have found a solution for the malformed ID issue. Terraform performs state validation so when the rule's ID is empty, it raises an error and exits. I found out that by providing a fake ID value that has `sgr-` prefix (I used `sgr-stub`), it was able to pass validation and reconcile successfully. Once the provider gets past the initial resource creation, the proper SGR ID is populated in the state file and the external name as expected. Tested successfully in my own cluster.

I also moved the resources into the `ec2` group.

2023-09-28 08:36 UTC, turkenf commented
/test-examples="examples/vpc/securitygroupegressrule.yaml"

2023-09-28 08:36 UTC, turkenf commented
/test-examples="examples/vpc/securitygroupingressrule.yaml"

2023-09-28 10:42 UTC, turkenf commented
/test-examples="examples/ec2/vpcsecuritygroupegressrule.yaml"

2023-09-28 10:43 UTC, turkenf commented
/test-examples="examples/ec2/vpcsecuritygroupingressrule.yaml"

2023-10-09 15:17 UTC, turkenf commented
/test-examples="examples/ec2/vpcsecuritygroupingressrule.yaml"

2023-10-10 05:58 UTC, huynhsontung commented on config/ec2/config.go
> +	p.AddResourceConfigurator("aws_vpc_security_group_ingress_rule", func(r *config.Resource) {
Totally agree.

2023-10-10 06:32 UTC, huynhsontung commented on config/ec2/config.go
> +			Type: "github.com/upbound/provider-aws/apis/ec2/v1beta1.SecurityGroup",
I missed updating these references when moving the resources from the `vpc` to `ec2` group. I think we can use `Type: "SecurityGroup"` now that they are all in the same `ec2` group, similar to other configs in this file.

2023-10-10 07:19 UTC, turkenf commented
/test-examples="examples/ec2/vpcsecuritygroupingressrule.yaml"

2023-10-10 07:28 UTC, turkenf commented
/test-examples="examples/ec2/securitygroupingressrule.yaml"

2023-10-10 08:11 UTC, turkenf commented
/test-examples="examples/ec2/securitygroupegressrule.yaml"

2023-10-10 08:44 UTC, huynhsontung commented
Apply is failing after rebase. I will debug this on my end. Not sure why import didn't pass.

2023-10-10 08:53 UTC, huynhsontung commented
@turkenf To speed up the debug process, would you mind rerunning the uptest on one of the resources?

2023-10-10 09:06 UTC, turkenf commented
> Apply is failing after rebase. I will debug this on my end. Not sure why import didn't pass.

With the latest uptest update, update and import tests were added to automatic testing, these were not tested before. Have you done the import test of the resources locally?

2023-10-10 09:06 UTC, turkenf commented
/test-examples="examples/ec2/securitygroupingressrule.yaml"

2023-10-10 09:20 UTC, huynhsontung commented
> With the latest uptest update, update and import tests were added to automatic testing, these were not tested before. Have you done the import test of the resources locally?

I tested import before rebase. I can see from the log that the `atProvider` object is populated. The test failed when [trying to check the VPC ID](https://github.com/upbound/provider-aws/actions/runs/6466512888/job/17554755330#step:10:5130).

2023-10-10 09:31 UTC, turkenf commented
@huynhsontung, could you please rebase again after this [PR](https://github.com/upbound/provider-aws/pull/914) merged and revert the external name change?

2023-10-10 11:53 UTC, turkenf commented on config/ec2/config.go
> +			Type: "github.com/upbound/provider-aws/apis/ec2/v1beta1.SecurityGroup",
It can stay this way, but the safest way to set references is to use `TerraformName`.

2023-10-10 12:36 UTC, turkenf commented
/test-examples="examples/ec2/securitygroupingressrule.yaml"

2023-10-10 12:59 UTC, turkenf approved these changes
Thank you so much for your effort in this PR @huynhsontung, LGTM.

2023-10-10 13:03 UTC, jeanduplessis approved these changes

2023-10-10 13:05 UTC, merged