Fix ses smtp accesskey
upbound/provider-aws pull request #718
Opened 2023-05-30 13:05 UTC by alexinthesky

### Description of your changes

re-add region to aws_iam_access_key
Fixes #717

I have:

- [X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

2023-06-08 10:01 UTC, turkenh reviewed
Thank you for your contribution @alexinthesky 🙌

2023-06-09 12:50 UTC, turkenf commented on config/overrides.go
>  	return func(r *config.Resource) {
Fixed.

2023-06-09 12:50 UTC, turkenf commented on config/overrides.go
> +		if (r.ShortGroup == "iam" || r.ShortGroup == "opsworks") && r.Name != "aws_iam_access_key" {
Done.

2023-06-09 13:04 UTC, turkenf commented
/test-examples="examples/iam/user.yaml"

2023-06-09 13:21 UTC, turkenh requested changes
Hmm, this would indeed be a breaking change for IAM AccessKey resource users since their existing resource will start failing with the lack of `region` parameter.

I think we would also need to add it as optional instead of required.

2023-06-13 11:06 UTC, alexinthesky commented
yeah this is even breaking everything in iam group

2023-07-21 09:07 UTC, turkenf commented
Hi, @alexinthesky are you still interested in moving this PR forward?

2023-09-27 16:11 UTC, turkenf commented
@alexinthesky, I'm closing this PR for now, if you're still interested and want to move it forward, feel free to reopen it.

2023-09-27 16:11 UTC, closed without merging

2024-02-15 23:21 UTC, tdjordan commented
I am running into a situation where I want to create an AccessKey for a User but get the `ses_smtp_password_v4` for a different region than what is generated by default.

For example, the `ses_smtp_password_v4` for `us-west-2` instead of the currently generated one for `us-east-2`.

I am interested in re-opening this PR to allow the region to be specified for the `aws_iam_access_key` resource.

What is needed for me to do to help drive this PR into an acceptable merge state?

I have little experience in `go` but am willing to learn and facilitate.

Alternatively, I have looked at the surrounding code and it is currently unclear to me what is populating the Region in the AWSCLient context. Could someone point me in the right direction?